<?php

/**
 * Implements hook_theme().
 */
function legacy_hooks_theme() {
  return [
    'legacy_template' => [
      'variables' => ['message' => NULL],
    ],
  ];
}


/**
 * Implements hook_help().
 */
function legacy_hooks_help($route_name, $route_parameters) {
    switch ($route_name) {
      case 'help.page.legacy_hooks':
        return '<p>This module demonstrates the legacy way of implementing theme hooks in Drupal.</p>';
    }
  }
  

